default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: manomoybiswas
  password: root

development:
  <<: *default
  database: music_label_development

test:
  <<: *default
  database: music_label_test

production:
  <<: *default
  database: music_label_production
  username: music_label
  password: <%= ENV['MUSIC_LABEL_DATABASE_PASSWORD'] %>
